### ISSUE TITLE
Fail to config after installation

### ISSUE THREAD

**Issue by thematrixdev** [tsunglung/foodpanda#1]
Hello there,

I have installed the integration from HACS, restarted HA.

Adding the integration, it shows an error immediately, without showing any configuration screen.

![image](https://github.com/tsunglung/foodpanda/assets/19472561/93ab8d75-1621-445b-bba5-2ddef7c0a647)

HA version 2024.1.2

Thanks.

**Comment by niceboygithub** [comment]
Please try to update to latest and try again.

**Comment by tsunglung** [comment]
Fixed in the latest commit.

**Comment by thematrixdev** [comment]
same
![image](https://github.com/tsunglung/foodpanda/assets/19472561/a36b32f2-797d-48ae-903d-a851ccd4c996)

```2024-02-17 19:40:49.307 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.foodpanda.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/foodpanda/__init__.py", line 30, in <module>
    from .data import foodpandaData
  File "/config/custom_components/foodpanda/data.py", line 113
    url=f"{LOGIN_URLS["tw"]}/login",
                       ^^
SyntaxError: f-string: unmatched '['
2024-02-17 19:40:49.312 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration foodpanda: Exception importing custom_components.foodpanda.config_flow
```

**Comment by tsunglung** [comment]
Please redownload again.

**Comment by thematrixdev** [comment]
Thanks.
